/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <system_stm32f4xx.h>
#include <stdint.h>
#include <stdlib.h>
#include <timer.h>
#include <time.h>
#include <ucglib.h>
#include <button.h>
#include <eventbutton.h>

#include <stdio.h>
#include <stdlib.h>

#include "boardconfig.h"
#include "drivers/gpio.h"
#include "drivers/timebase.h"
#include "periph/led.h"
#include "periph/buzzer.h"
#include "periph/button.h"
#include "graphic/display_init.h"
#include "game/menu_ui.h"
#include "game/run_game.h"


int main(void)
{
    Timebase_Init();
    GPIO_EnableAllClocks();

    LED_Init();
    Buzzer_Init();
    Button_Init();
    Display_Init();

    while(1)
    {
    	UI_ShowMenu();
    	run_game();
    }
}
